# Generated by Django 5.1.6 on 2025-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateprofile_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
